// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrKciSyw6at5gfBF_E2bn8EsJRj58vp0',
    appId: '1:744172179776:web:35854407f3ba6321d6aaa5',
    messagingSenderId: '744172179776',
    projectId: 'smart-canteen-73a77',
    authDomain: 'smart-canteen-73a77.firebaseapp.com',
    storageBucket: 'smart-canteen-73a77.firebasestorage.app',
    measurementId: 'G-NCEEBGK3M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_dDNeOHg5iyvKXF4OSW_ToMjFWY7oHo',
    appId: '1:744172179776:android:ba346cd85d8d217cd6aaa5',
    messagingSenderId: '744172179776',
    projectId: 'smart-canteen-73a77',
    storageBucket: 'smart-canteen-73a77.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxvUBxkKp2vsnaoLNSf4cAk0VqrRKvZs',
    appId: '1:744172179776:ios:8c9bc50d619b6b21d6aaa5',
    messagingSenderId: '744172179776',
    projectId: 'smart-canteen-73a77',
    storageBucket: 'smart-canteen-73a77.firebasestorage.app',
    iosBundleId: 'com.ucstt.smartcanteenuser',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuxvUBxkKp2vsnaoLNSf4cAk0VqrRKvZs',
    appId: '1:744172179776:ios:71f23ad5fd7998ddd6aaa5',
    messagingSenderId: '744172179776',
    projectId: 'smart-canteen-73a77',
    storageBucket: 'smart-canteen-73a77.firebasestorage.app',
    iosBundleId: 'com.example.smartcanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSrKciSyw6at5gfBF_E2bn8EsJRj58vp0',
    appId: '1:744172179776:web:8ad50ed80ee20c74d6aaa5',
    messagingSenderId: '744172179776',
    projectId: 'smart-canteen-73a77',
    authDomain: 'smart-canteen-73a77.firebaseapp.com',
    storageBucket: 'smart-canteen-73a77.firebasestorage.app',
    measurementId: 'G-EPMVRBW197',
  );
}
