// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDjLo5FB6-AJmdqh_FSgJk-n1sX965H4',
    appId: '1:344438064119:web:7413348c73e1eedc2b24f2',
    messagingSenderId: '344438064119',
    projectId: 'smart-canteen-b9e53',
    authDomain: 'smart-canteen-b9e53.firebaseapp.com',
    storageBucket: 'smart-canteen-b9e53.firebasestorage.app',
    measurementId: 'G-TMWGTBVNDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGNdz4Dqia3tpAKFXJSiSkSaPYzeBpVeM',
    appId: '1:344438064119:android:9b8d612b80ef17702b24f2',
    messagingSenderId: '344438064119',
    projectId: 'smart-canteen-b9e53',
    storageBucket: 'smart-canteen-b9e53.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6rXviL3u4oisMSxvkJ-w8b_oTkfT8Wc',
    appId: '1:344438064119:ios:dd34080d20f575942b24f2',
    messagingSenderId: '344438064119',
    projectId: 'smart-canteen-b9e53',
    storageBucket: 'smart-canteen-b9e53.firebasestorage.app',
    iosBundleId: 'com.example.smartcanteen',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6rXviL3u4oisMSxvkJ-w8b_oTkfT8Wc',
    appId: '1:344438064119:ios:dd34080d20f575942b24f2',
    messagingSenderId: '344438064119',
    projectId: 'smart-canteen-b9e53',
    storageBucket: 'smart-canteen-b9e53.firebasestorage.app',
    iosBundleId: 'com.example.smartcanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDDjLo5FB6-AJmdqh_FSgJk-n1sX965H4',
    appId: '1:344438064119:web:84557aa1f74888c82b24f2',
    messagingSenderId: '344438064119',
    projectId: 'smart-canteen-b9e53',
    authDomain: 'smart-canteen-b9e53.firebaseapp.com',
    storageBucket: 'smart-canteen-b9e53.firebasestorage.app',
    measurementId: 'G-CYQM5WKH6P',
  );
}
